// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.0
// source: FeatureChaos.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All  int32            `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Name string           `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Item map[string]int32 `protobuf:"bytes,3,rep,name=Item,proto3" json:"Item,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *PropsItem) Reset() {
	*x = PropsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FeatureChaos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropsItem) ProtoMessage() {}

func (x *PropsItem) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropsItem.ProtoReflect.Descriptor instead.
func (*PropsItem) Descriptor() ([]byte, []int) {
	return file_FeatureChaos_proto_rawDescGZIP(), []int{0}
}

func (x *PropsItem) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *PropsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropsItem) GetItem() map[string]int32 {
	if x != nil {
		return x.Item
	}
	return nil
}

type FeatureItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All   int32        `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Name  string       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Props []*PropsItem `protobuf:"bytes,3,rep,name=Props,proto3" json:"Props,omitempty"`
}

func (x *FeatureItem) Reset() {
	*x = FeatureItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FeatureChaos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureItem) ProtoMessage() {}

func (x *FeatureItem) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureItem.ProtoReflect.Descriptor instead.
func (*FeatureItem) Descriptor() ([]byte, []int) {
	return file_FeatureChaos_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureItem) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *FeatureItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeatureItem) GetProps() []*PropsItem {
	if x != nil {
		return x.Props
	}
	return nil
}

type GetAllFeatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	LastVersion int64  `protobuf:"varint,2,opt,name=LastVersion,proto3" json:"LastVersion,omitempty"`
}

func (x *GetAllFeatureRequest) Reset() {
	*x = GetAllFeatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FeatureChaos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFeatureRequest) ProtoMessage() {}

func (x *GetAllFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFeatureRequest.ProtoReflect.Descriptor instead.
func (*GetAllFeatureRequest) Descriptor() ([]byte, []int) {
	return file_FeatureChaos_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllFeatureRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetAllFeatureRequest) GetLastVersion() int64 {
	if x != nil {
		return x.LastVersion
	}
	return 0
}

type SendStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	FeatureName string `protobuf:"bytes,2,opt,name=FeatureName,proto3" json:"FeatureName,omitempty"`
}

func (x *SendStatsRequest) Reset() {
	*x = SendStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FeatureChaos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStatsRequest) ProtoMessage() {}

func (x *SendStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStatsRequest.ProtoReflect.Descriptor instead.
func (*SendStatsRequest) Descriptor() ([]byte, []int) {
	return file_FeatureChaos_proto_rawDescGZIP(), []int{3}
}

func (x *SendStatsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SendStatsRequest) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

type GetFeatureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  int64          `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Features []*FeatureItem `protobuf:"bytes,2,rep,name=Features,proto3" json:"Features,omitempty"`
}

func (x *GetFeatureResponse) Reset() {
	*x = GetFeatureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_FeatureChaos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeatureResponse) ProtoMessage() {}

func (x *GetFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeatureResponse.ProtoReflect.Descriptor instead.
func (*GetFeatureResponse) Descriptor() ([]byte, []int) {
	return file_FeatureChaos_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeatureResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetFeatureResponse) GetFeatures() []*FeatureItem {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_FeatureChaos_proto protoreflect.FileDescriptor

var file_FeatureChaos_proto_rawDesc = []byte{
	0x0a, 0x12, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6f, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61,
	0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa1, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a,
	0x03, 0x41, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41, 0x6c, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6f, 0x73,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x37, 0x0a, 0x09, 0x49, 0x74,
	0x65, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x62, 0x0a, 0x0b, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x41, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x70,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x43, 0x68, 0x61, 0x6f, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x22, 0x5a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x56, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x65, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6f, 0x73, 0x2e, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x32, 0xa8, 0x01, 0x0a, 0x0e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x12, 0x22, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61, 0x6f,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x43, 0x68, 0x61, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x68, 0x61,
	0x6f, 0x73, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x42, 0x3b, 0x5a,
	0x39, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x70,
	0x72, 0x6f, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x69, 0x6f, 0x2f, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x43, 0x68, 0x61, 0x6f, 0x73, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x66, 0x63, 0x5f, 0x73, 0x64,
	0x6b, 0x5f, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_FeatureChaos_proto_rawDescOnce sync.Once
	file_FeatureChaos_proto_rawDescData = file_FeatureChaos_proto_rawDesc
)

func file_FeatureChaos_proto_rawDescGZIP() []byte {
	file_FeatureChaos_proto_rawDescOnce.Do(func() {
		file_FeatureChaos_proto_rawDescData = protoimpl.X.CompressGZIP(file_FeatureChaos_proto_rawDescData)
	})
	return file_FeatureChaos_proto_rawDescData
}

var file_FeatureChaos_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_FeatureChaos_proto_goTypes = []any{
	(*PropsItem)(nil),            // 0: FeatureChaos.PropsItem
	(*FeatureItem)(nil),          // 1: FeatureChaos.FeatureItem
	(*GetAllFeatureRequest)(nil), // 2: FeatureChaos.GetAllFeatureRequest
	(*SendStatsRequest)(nil),     // 3: FeatureChaos.SendStatsRequest
	(*GetFeatureResponse)(nil),   // 4: FeatureChaos.GetFeatureResponse
	nil,                          // 5: FeatureChaos.PropsItem.ItemEntry
	(*emptypb.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_FeatureChaos_proto_depIdxs = []int32{
	5, // 0: FeatureChaos.PropsItem.Item:type_name -> FeatureChaos.PropsItem.ItemEntry
	0, // 1: FeatureChaos.FeatureItem.Props:type_name -> FeatureChaos.PropsItem
	1, // 2: FeatureChaos.GetFeatureResponse.Features:type_name -> FeatureChaos.FeatureItem
	2, // 3: FeatureChaos.FeatureService.Subscribe:input_type -> FeatureChaos.GetAllFeatureRequest
	3, // 4: FeatureChaos.FeatureService.Stats:input_type -> FeatureChaos.SendStatsRequest
	4, // 5: FeatureChaos.FeatureService.Subscribe:output_type -> FeatureChaos.GetFeatureResponse
	6, // 6: FeatureChaos.FeatureService.Stats:output_type -> google.protobuf.Empty
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_FeatureChaos_proto_init() }
func file_FeatureChaos_proto_init() {
	if File_FeatureChaos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_FeatureChaos_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PropsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FeatureChaos_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FeatureItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FeatureChaos_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllFeatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FeatureChaos_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SendStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_FeatureChaos_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetFeatureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_FeatureChaos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_FeatureChaos_proto_goTypes,
		DependencyIndexes: file_FeatureChaos_proto_depIdxs,
		MessageInfos:      file_FeatureChaos_proto_msgTypes,
	}.Build()
	File_FeatureChaos_proto = out.File
	file_FeatureChaos_proto_rawDesc = nil
	file_FeatureChaos_proto_goTypes = nil
	file_FeatureChaos_proto_depIdxs = nil
}
