<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FeatureChaos.proto

namespace FeatureChaos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FeatureChaos.FeatureItem</code>
 */
class FeatureItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 All = 1;</code>
     */
    protected $All = 0;
    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    protected $Name = '';
    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.PropsItem Props = 3;</code>
     */
    private $Props;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $All
     *     @type string $Name
     *     @type array<\FeatureChaos\PropsItem>|\Google\Protobuf\Internal\RepeatedField $Props
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FeatureChaos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 All = 1;</code>
     * @return int
     */
    public function getAll()
    {
        return $this->All;
    }

    /**
     * Generated from protobuf field <code>int32 All = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAll($var)
    {
        GPBUtil::checkInt32($var);
        $this->All = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.PropsItem Props = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProps()
    {
        return $this->Props;
    }

    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.PropsItem Props = 3;</code>
     * @param array<\FeatureChaos\PropsItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FeatureChaos\PropsItem::class);
        $this->Props = $arr;

        return $this;
    }

}

