<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FeatureChaos.proto

namespace FeatureChaos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>FeatureChaos.GetFeatureResponse</code>
 */
class GetFeatureResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 Version = 1;</code>
     */
    protected $Version = 0;
    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.FeatureItem Features = 2;</code>
     */
    private $Features;
    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.GetFeatureResponse.DeletedItem Deleted = 3;</code>
     */
    private $Deleted;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $Version
     *     @type \FeatureChaos\FeatureItem[] $Features
     *     @type \FeatureChaos\GetFeatureResponse\DeletedItem[] $Deleted
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FeatureChaos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 Version = 1;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->Version;
    }

    /**
     * Generated from protobuf field <code>int64 Version = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->Version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.FeatureItem Features = 2;</code>
     * @return RepeatedField<\FeatureChaos\FeatureItem>
     */
    public function getFeatures()
    {
        return $this->Features;
    }

    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.FeatureItem Features = 2;</code>
     * @param \FeatureChaos\FeatureItem[] $var
     * @return $this
     */
    public function setFeatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FeatureChaos\FeatureItem::class);
        $this->Features = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.GetFeatureResponse.DeletedItem Deleted = 3;</code>
     * @return RepeatedField<\FeatureChaos\GetFeatureResponse\DeletedItem>
     */
    public function getDeleted()
    {
        return $this->Deleted;
    }

    /**
     * Generated from protobuf field <code>repeated .FeatureChaos.GetFeatureResponse.DeletedItem Deleted = 3;</code>
     * @param \FeatureChaos\GetFeatureResponse\DeletedItem[] $var
     * @return $this
     */
    public function setDeleted($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FeatureChaos\GetFeatureResponse\DeletedItem::class);
        $this->Deleted = $arr;

        return $this;
    }

}

