<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FeatureChaos.proto

namespace FeatureChaos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>FeatureChaos.PropsItem</code>
 */
class PropsItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 All = 1;</code>
     */
    protected $All = 0;
    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    protected $Name = '';
    /**
     * Generated from protobuf field <code>map<string, int32> Item = 3;</code>
     */
    private $Item;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $All
     *     @type string $Name
     *     @type array|\Google\Protobuf\Internal\MapField $Item
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FeatureChaos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 All = 1;</code>
     * @return int
     */
    public function getAll()
    {
        return $this->All;
    }

    /**
     * Generated from protobuf field <code>int32 All = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAll($var)
    {
        GPBUtil::checkInt32($var);
        $this->All = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> Item = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItem()
    {
        return $this->Item;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> Item = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItem($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->Item = $arr;

        return $this;
    }

}

