// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//  	protoc-gen-go v1.34.2
//  	protoc        v5.27.3
// source: FeatureChaos.proto

package pb

import (
	reflect "reflect"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All  int32            `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Name string           `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Item map[string]int32 `protobuf:"bytes,3,rep,name=Item,proto3" json:"Item,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *PropsItem) Reset()         { *x = PropsItem{} }
func (x *PropsItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (*PropsItem) ProtoMessage()    {}
func (x *PropsItem) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// getters for convenience
func (x *PropsItem) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}
func (x *PropsItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *PropsItem) GetItem() map[string]int32 {
	if x != nil {
		return x.Item
	}
	return nil
}

type FeatureItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	All   int32        `protobuf:"varint,1,opt,name=All,proto3" json:"All,omitempty"`
	Name  string       `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Props []*PropsItem `protobuf:"bytes,3,rep,name=Props,proto3" json:"Props,omitempty"`
}

func (x *FeatureItem) Reset()         { *x = FeatureItem{} }
func (x *FeatureItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (*FeatureItem) ProtoMessage()    {}
func (x *FeatureItem) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// getters for convenience
func (x *FeatureItem) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}
func (x *FeatureItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *FeatureItem) GetProps() []*PropsItem {
	if x != nil {
		return x.Props
	}
	return nil
}

type GetAllFeatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	LastVersion int64  `protobuf:"varint,2,opt,name=LastVersion,proto3" json:"LastVersion,omitempty"`
}

func (x *GetAllFeatureRequest) Reset()         { *x = GetAllFeatureRequest{} }
func (x *GetAllFeatureRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetAllFeatureRequest) ProtoMessage()    {}
func (x *GetAllFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SendStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	FeatureName string `protobuf:"bytes,2,opt,name=FeatureName,proto3" json:"FeatureName,omitempty"`
}

func (x *SendStatsRequest) Reset()         { *x = SendStatsRequest{} }
func (x *SendStatsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*SendStatsRequest) ProtoMessage()    {}
func (x *SendStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetFeatureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  int64          `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Features []*FeatureItem `protobuf:"bytes,2,rep,name=Features,proto3" json:"Features,omitempty"`
}

func (x *GetFeatureResponse) Reset()         { *x = GetFeatureResponse{} }
func (x *GetFeatureResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetFeatureResponse) ProtoMessage()    {}
func (x *GetFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_FeatureChaos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// helper getters for compatibility with server SDK usage
func (x *GetFeatureResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}
func (x *GetFeatureResponse) GetFeatures() []*FeatureItem {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_FeatureChaos_proto protoreflect.FileDescriptor

var file_FeatureChaos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_FeatureChaos_proto_goTypes = []any{
	(*PropsItem)(nil),            // 0: FeatureChaos.PropsItem
	(*FeatureItem)(nil),          // 1: FeatureChaos.FeatureItem
	(*GetAllFeatureRequest)(nil), // 2: FeatureChaos.GetAllFeatureRequest
	(*SendStatsRequest)(nil),     // 3: FeatureChaos.SendStatsRequest
	(*GetFeatureResponse)(nil),   // 4: FeatureChaos.GetFeatureResponse
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}

func init() { file_FeatureChaos_proto_init() }
func file_FeatureChaos_proto_init() {
	if File_FeatureChaos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: nil,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:      file_FeatureChaos_proto_goTypes,
		MessageInfos: file_FeatureChaos_proto_msgTypes,
	}.Build()
	File_FeatureChaos_proto = out.File
}
