<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FeatureChaos.proto

namespace GPBMetadata;

class FeatureChaos
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x93\x05\x0A\x12FeatureChaos.proto\x12\x0CFeatureChaos\"\x84\x01\x0A\x09PropsItem\x12\x0B\x0A\x03All\x18\x01 \x01(\x05\x12\x0C\x0A\x04Name\x18\x02 \x01(\x09\x12/\x0A\x04Item\x18\x03 \x03(\x0B2!.FeatureChaos.PropsItem.ItemEntry\x1A+\x0A\x09ItemEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x05:\x028\x01\"P\x0A\x0BFeatureItem\x12\x0B\x0A\x03All\x18\x01 \x01(\x05\x12\x0C\x0A\x04Name\x18\x02 \x01(\x09\x12&\x0A\x05Props\x18\x03 \x03(\x0B2\x17.FeatureChaos.PropsItem\"@\x0A\x14GetAllFeatureRequest\x12\x13\x0A\x0BServiceName\x18\x01 \x01(\x09\x12\x13\x0A\x0BLastVersion\x18\x02 \x01(\x03\"<\x0A\x10SendStatsRequest\x12\x13\x0A\x0BServiceName\x18\x01 \x01(\x09\x12\x13\x0A\x0BFeatureName\x18\x02 \x01(\x09\"R\x0A\x12GetFeatureResponse\x12\x0F\x0A\x07Version\x18\x01 \x01(\x03\x12+\x0A\x08Features\x18\x02 \x03(\x0B2\x19.FeatureChaos.FeatureItem2\xA8\x01\x0A\x0EFeatureService\x12S\x0A\x09Subscribe\x12\".FeatureChaos.GetAllFeatureRequest\x1A .FeatureChaos.GetFeatureResponse0\x01\x12A\x0A\x05Stats\x12\x1E.FeatureChaos.SendStatsRequest\x1A\x16.google.protobuf.Empty(\x01B\x0FZ\x0D/FeatureChaosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

