<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FeatureChaos.proto

namespace FeatureChaos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>FeatureChaos.SendStatsRequest</code>
 */
class SendStatsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ServiceName = 1;</code>
     */
    protected $ServiceName = '';
    /**
     * Generated from protobuf field <code>string FeatureName = 2;</code>
     */
    protected $FeatureName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ServiceName
     *     @type string $FeatureName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FeatureChaos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ServiceName = 1;</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->ServiceName;
    }

    /**
     * Generated from protobuf field <code>string ServiceName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ServiceName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FeatureName = 2;</code>
     * @return string
     */
    public function getFeatureName()
    {
        return $this->FeatureName;
    }

    /**
     * Generated from protobuf field <code>string FeatureName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFeatureName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FeatureName = $var;

        return $this;
    }

}

