<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FeatureChaos.proto

namespace FeatureChaos\GetFeatureResponse\DeletedItem;

use UnexpectedValueException;

/**
 * Protobuf type <code>FeatureChaos.GetFeatureResponse.DeletedItem.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>FEATURE = 0;</code>
     */
    const FEATURE = 0;
    /**
     * Generated from protobuf enum <code>KEY = 1;</code>
     */
    const KEY = 1;
    /**
     * Generated from protobuf enum <code>PARAM = 2;</code>
     */
    const PARAM = 2;

    private static $valueToName = [
        self::FEATURE => 'FEATURE',
        self::KEY => 'KEY',
        self::PARAM => 'PARAM',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

