<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FeatureChaos.proto

namespace FeatureChaos\GetFeatureResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Explicit deletions since last version
 *
 * Generated from protobuf message <code>FeatureChaos.GetFeatureResponse.DeletedItem</code>
 */
class DeletedItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.FeatureChaos.GetFeatureResponse.DeletedItem.Type Kind = 1;</code>
     */
    protected $Kind = 0;
    /**
     * Generated from protobuf field <code>string FeatureName = 2;</code>
     */
    protected $FeatureName = '';
    /**
     * for KEY and PARAM deletions
     *
     * Generated from protobuf field <code>string KeyName = 3;</code>
     */
    protected $KeyName = '';
    /**
     * for PARAM deletions
     *
     * Generated from protobuf field <code>string ParamName = 4;</code>
     */
    protected $ParamName = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Kind
     *     @type string $FeatureName
     *     @type string $KeyName
     *           for KEY and PARAM deletions
     *     @type string $ParamName
     *           for PARAM deletions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\FeatureChaos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.FeatureChaos.GetFeatureResponse.DeletedItem.Type Kind = 1;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->Kind;
    }

    /**
     * Generated from protobuf field <code>.FeatureChaos.GetFeatureResponse.DeletedItem.Type Kind = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \FeatureChaos\GetFeatureResponse\DeletedItem\Type::class);
        $this->Kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FeatureName = 2;</code>
     * @return string
     */
    public function getFeatureName()
    {
        return $this->FeatureName;
    }

    /**
     * Generated from protobuf field <code>string FeatureName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFeatureName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FeatureName = $var;

        return $this;
    }

    /**
     * for KEY and PARAM deletions
     *
     * Generated from protobuf field <code>string KeyName = 3;</code>
     * @return string
     */
    public function getKeyName()
    {
        return $this->KeyName;
    }

    /**
     * for KEY and PARAM deletions
     *
     * Generated from protobuf field <code>string KeyName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->KeyName = $var;

        return $this;
    }

    /**
     * for PARAM deletions
     *
     * Generated from protobuf field <code>string ParamName = 4;</code>
     * @return string
     */
    public function getParamName()
    {
        return $this->ParamName;
    }

    /**
     * for PARAM deletions
     *
     * Generated from protobuf field <code>string ParamName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParamName($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParamName = $var;

        return $this;
    }

}

